<?xml version="1.0" encoding = "Windows-1252"?>
<VisualStudioProject
	ProjectType="Visual C++"
	Version="7.10"
	Name="GenFixPrivs"
	SccProjectName=""
	SccLocalPath=""
	Keyword="Win32Proj">
	<Platforms>
		<Platform
			Name="Win32"/>
	</Platforms>
	<Configurations>
		<Configuration
			Name="Debug|Win32"
			OutputDirectory="Debug"
			IntermediateDirectory="GenFixPrivs.dir\Debug"
			ConfigurationType="10"
			UseOfMFC="0"
			ATLMinimizesCRunTimeLibraryUsage="FALSE"
			CharacterSet="2">
			<Tool
				Name="VCCLCompilerTool"
				AdditionalIncludeDirectories=""
				ExceptionHandling="FALSE"
				PreprocessorDefinitions="CMAKE_BUILD,HAVE_YASSL,HAVE_ARCHIVE_DB,HAVE_BLACKHOLE_DB,HAVE_EXAMPLE_DB,HAVE_FEDERATED_DB,HAVE_INNOBASE_DB,__NT__,_WINDOWS,__WIN__,_CRT_SECURE_NO_DEPRECATE,&quot;CMAKE_INTDIR=\&quot;Debug\&quot;&quot;"
				AssemblerListingLocation="Debug"
				ObjectFile="$(IntDir)\"
/>
			<Tool
				Name="VCCustomBuildTool"/>
			<Tool
				Name="VCResourceCompilerTool"
				AdditionalIncludeDirectories=""
				PreprocessorDefinitions="CMAKE_BUILD,HAVE_YASSL,HAVE_ARCHIVE_DB,HAVE_BLACKHOLE_DB,HAVE_EXAMPLE_DB,HAVE_FEDERATED_DB,HAVE_INNOBASE_DB,__NT__,_WINDOWS,__WIN__,_CRT_SECURE_NO_DEPRECATE,&quot;CMAKE_INTDIR=\&quot;Debug\&quot;&quot;"/>
			<Tool
				Name="VCMIDLTool"
				PreprocessorDefinitions="CMAKE_BUILD,HAVE_YASSL,HAVE_ARCHIVE_DB,HAVE_BLACKHOLE_DB,HAVE_EXAMPLE_DB,HAVE_FEDERATED_DB,HAVE_INNOBASE_DB,__NT__,_WINDOWS,__WIN__,_CRT_SECURE_NO_DEPRECATE,&quot;CMAKE_INTDIR=\&quot;Debug\&quot;&quot;"
				MkTypLibCompatible="FALSE"
				TargetEnvironment="1"
				GenerateStublessProxies="TRUE"
				TypeLibraryName="$(InputName).tlb"
				OutputDirectory="$(IntDir)"
				HeaderFileName="$(InputName).h"
				DLLDataFileName=""
				InterfaceIdentifierFileName="$(InputName)_i.c"
				ProxyFileName="$(InputName)_p.c"/>
			<Tool
				Name="VCPreBuildEventTool"/>
			<Tool
				Name="VCPreLinkEventTool"/>
			<Tool
				Name="VCPostBuildEventTool"/>
		</Configuration>
		<Configuration
			Name="Release|Win32"
			OutputDirectory="Release"
			IntermediateDirectory="GenFixPrivs.dir\Release"
			ConfigurationType="10"
			UseOfMFC="0"
			ATLMinimizesCRunTimeLibraryUsage="FALSE"
			CharacterSet="2">
			<Tool
				Name="VCCLCompilerTool"
				AdditionalIncludeDirectories=""
				ExceptionHandling="FALSE"
				PreprocessorDefinitions="CMAKE_BUILD,HAVE_YASSL,HAVE_ARCHIVE_DB,HAVE_BLACKHOLE_DB,HAVE_EXAMPLE_DB,HAVE_FEDERATED_DB,HAVE_INNOBASE_DB,__NT__,_WINDOWS,__WIN__,_CRT_SECURE_NO_DEPRECATE,&quot;CMAKE_INTDIR=\&quot;Release\&quot;&quot;"
				AssemblerListingLocation="Release"
				ObjectFile="$(IntDir)\"
/>
			<Tool
				Name="VCCustomBuildTool"/>
			<Tool
				Name="VCResourceCompilerTool"
				AdditionalIncludeDirectories=""
				PreprocessorDefinitions="CMAKE_BUILD,HAVE_YASSL,HAVE_ARCHIVE_DB,HAVE_BLACKHOLE_DB,HAVE_EXAMPLE_DB,HAVE_FEDERATED_DB,HAVE_INNOBASE_DB,__NT__,_WINDOWS,__WIN__,_CRT_SECURE_NO_DEPRECATE,&quot;CMAKE_INTDIR=\&quot;Release\&quot;&quot;"/>
			<Tool
				Name="VCMIDLTool"
				PreprocessorDefinitions="CMAKE_BUILD,HAVE_YASSL,HAVE_ARCHIVE_DB,HAVE_BLACKHOLE_DB,HAVE_EXAMPLE_DB,HAVE_FEDERATED_DB,HAVE_INNOBASE_DB,__NT__,_WINDOWS,__WIN__,_CRT_SECURE_NO_DEPRECATE,&quot;CMAKE_INTDIR=\&quot;Release\&quot;&quot;"
				MkTypLibCompatible="FALSE"
				TargetEnvironment="1"
				GenerateStublessProxies="TRUE"
				TypeLibraryName="$(InputName).tlb"
				OutputDirectory="$(IntDir)"
				HeaderFileName="$(InputName).h"
				DLLDataFileName=""
				InterfaceIdentifierFileName="$(InputName)_i.c"
				ProxyFileName="$(InputName)_p.c"/>
			<Tool
				Name="VCPreBuildEventTool"/>
			<Tool
				Name="VCPreLinkEventTool"/>
			<Tool
				Name="VCPostBuildEventTool"/>
		</Configuration>
		<Configuration
			Name="MinSizeRel|Win32"
			OutputDirectory="MinSizeRel"
			IntermediateDirectory="GenFixPrivs.dir\MinSizeRel"
			ConfigurationType="10"
			UseOfMFC="0"
			ATLMinimizesCRunTimeLibraryUsage="FALSE"
			CharacterSet="2">
			<Tool
				Name="VCCLCompilerTool"
				AdditionalIncludeDirectories=""
				ExceptionHandling="FALSE"
				PreprocessorDefinitions="CMAKE_BUILD,HAVE_YASSL,HAVE_ARCHIVE_DB,HAVE_BLACKHOLE_DB,HAVE_EXAMPLE_DB,HAVE_FEDERATED_DB,HAVE_INNOBASE_DB,__NT__,_WINDOWS,__WIN__,_CRT_SECURE_NO_DEPRECATE,&quot;CMAKE_INTDIR=\&quot;MinSizeRel\&quot;&quot;"
				AssemblerListingLocation="MinSizeRel"
				ObjectFile="$(IntDir)\"
/>
			<Tool
				Name="VCCustomBuildTool"/>
			<Tool
				Name="VCResourceCompilerTool"
				AdditionalIncludeDirectories=""
				PreprocessorDefinitions="CMAKE_BUILD,HAVE_YASSL,HAVE_ARCHIVE_DB,HAVE_BLACKHOLE_DB,HAVE_EXAMPLE_DB,HAVE_FEDERATED_DB,HAVE_INNOBASE_DB,__NT__,_WINDOWS,__WIN__,_CRT_SECURE_NO_DEPRECATE,&quot;CMAKE_INTDIR=\&quot;MinSizeRel\&quot;&quot;"/>
			<Tool
				Name="VCMIDLTool"
				PreprocessorDefinitions="CMAKE_BUILD,HAVE_YASSL,HAVE_ARCHIVE_DB,HAVE_BLACKHOLE_DB,HAVE_EXAMPLE_DB,HAVE_FEDERATED_DB,HAVE_INNOBASE_DB,__NT__,_WINDOWS,__WIN__,_CRT_SECURE_NO_DEPRECATE,&quot;CMAKE_INTDIR=\&quot;MinSizeRel\&quot;&quot;"
				MkTypLibCompatible="FALSE"
				TargetEnvironment="1"
				GenerateStublessProxies="TRUE"
				TypeLibraryName="$(InputName).tlb"
				OutputDirectory="$(IntDir)"
				HeaderFileName="$(InputName).h"
				DLLDataFileName=""
				InterfaceIdentifierFileName="$(InputName)_i.c"
				ProxyFileName="$(InputName)_p.c"/>
			<Tool
				Name="VCPreBuildEventTool"/>
			<Tool
				Name="VCPreLinkEventTool"/>
			<Tool
				Name="VCPostBuildEventTool"/>
		</Configuration>
		<Configuration
			Name="RelWithDebInfo|Win32"
			OutputDirectory="RelWithDebInfo"
			IntermediateDirectory="GenFixPrivs.dir\RelWithDebInfo"
			ConfigurationType="10"
			UseOfMFC="0"
			ATLMinimizesCRunTimeLibraryUsage="FALSE"
			CharacterSet="2">
			<Tool
				Name="VCCLCompilerTool"
				AdditionalIncludeDirectories=""
				ExceptionHandling="FALSE"
				PreprocessorDefinitions="CMAKE_BUILD,HAVE_YASSL,HAVE_ARCHIVE_DB,HAVE_BLACKHOLE_DB,HAVE_EXAMPLE_DB,HAVE_FEDERATED_DB,HAVE_INNOBASE_DB,__NT__,_WINDOWS,__WIN__,_CRT_SECURE_NO_DEPRECATE,&quot;CMAKE_INTDIR=\&quot;RelWithDebInfo\&quot;&quot;"
				AssemblerListingLocation="RelWithDebInfo"
				ObjectFile="$(IntDir)\"
/>
			<Tool
				Name="VCCustomBuildTool"/>
			<Tool
				Name="VCResourceCompilerTool"
				AdditionalIncludeDirectories=""
				PreprocessorDefinitions="CMAKE_BUILD,HAVE_YASSL,HAVE_ARCHIVE_DB,HAVE_BLACKHOLE_DB,HAVE_EXAMPLE_DB,HAVE_FEDERATED_DB,HAVE_INNOBASE_DB,__NT__,_WINDOWS,__WIN__,_CRT_SECURE_NO_DEPRECATE,&quot;CMAKE_INTDIR=\&quot;RelWithDebInfo\&quot;&quot;"/>
			<Tool
				Name="VCMIDLTool"
				PreprocessorDefinitions="CMAKE_BUILD,HAVE_YASSL,HAVE_ARCHIVE_DB,HAVE_BLACKHOLE_DB,HAVE_EXAMPLE_DB,HAVE_FEDERATED_DB,HAVE_INNOBASE_DB,__NT__,_WINDOWS,__WIN__,_CRT_SECURE_NO_DEPRECATE,&quot;CMAKE_INTDIR=\&quot;RelWithDebInfo\&quot;&quot;"
				MkTypLibCompatible="FALSE"
				TargetEnvironment="1"
				GenerateStublessProxies="TRUE"
				TypeLibraryName="$(InputName).tlb"
				OutputDirectory="$(IntDir)"
				HeaderFileName="$(InputName).h"
				DLLDataFileName=""
				InterfaceIdentifierFileName="$(InputName)_i.c"
				ProxyFileName="$(InputName)_p.c"/>
			<Tool
				Name="VCPreBuildEventTool"/>
			<Tool
				Name="VCPreLinkEventTool"/>
			<Tool
				Name="VCPostBuildEventTool"/>
		</Configuration>
	</Configurations>
	<Files>
			<File
				RelativePath="F:\build\mysql-5.0.51a-winbuild\mysql-community-nt-5.0.51a-build\scripts\CMakeLists.txt">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCustomBuildTool"
					Description="Building Custom Rule F:/build/mysql-5.0.51a-winbuild/mysql-community-nt-5.0.51a-build/scripts/CMakeLists.txt"
					CommandLine="&quot;C:\Program Files\CMake 2.4\bin\cmake.exe&quot; -HF:/build/mysql-5.0.51a-winbuild/mysql-community-nt-5.0.51a-build -BF:/build/mysql-5.0.51a-winbuild/mysql-community-nt-5.0.51a-build"
					AdditionalDependencies="F:\build\mysql-5.0.51a-winbuild\mysql-community-nt-5.0.51a-build\scripts\CMakeLists.txt;&quot;C:\Program Files\CMake 2.4\share\cmake-2.4\Templates\CMakeWindowsSystemConfig.cmake&quot;;F:\build\mysql-5.0.51a-winbuild\mysql-community-nt-5.0.51a-build\scripts\CMakeLists.txt;"
					Outputs="comp_sql.vcproj.cmake"/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCustomBuildTool"
					Description="Building Custom Rule F:/build/mysql-5.0.51a-winbuild/mysql-community-nt-5.0.51a-build/scripts/CMakeLists.txt"
					CommandLine="&quot;C:\Program Files\CMake 2.4\bin\cmake.exe&quot; -HF:/build/mysql-5.0.51a-winbuild/mysql-community-nt-5.0.51a-build -BF:/build/mysql-5.0.51a-winbuild/mysql-community-nt-5.0.51a-build"
					AdditionalDependencies="F:\build\mysql-5.0.51a-winbuild\mysql-community-nt-5.0.51a-build\scripts\CMakeLists.txt;&quot;C:\Program Files\CMake 2.4\share\cmake-2.4\Templates\CMakeWindowsSystemConfig.cmake&quot;;F:\build\mysql-5.0.51a-winbuild\mysql-community-nt-5.0.51a-build\scripts\CMakeLists.txt;"
					Outputs="comp_sql.vcproj.cmake"/>
				</FileConfiguration>
				<FileConfiguration
					Name="MinSizeRel|Win32">
					<Tool
					Name="VCCustomBuildTool"
					Description="Building Custom Rule F:/build/mysql-5.0.51a-winbuild/mysql-community-nt-5.0.51a-build/scripts/CMakeLists.txt"
					CommandLine="&quot;C:\Program Files\CMake 2.4\bin\cmake.exe&quot; -HF:/build/mysql-5.0.51a-winbuild/mysql-community-nt-5.0.51a-build -BF:/build/mysql-5.0.51a-winbuild/mysql-community-nt-5.0.51a-build"
					AdditionalDependencies="F:\build\mysql-5.0.51a-winbuild\mysql-community-nt-5.0.51a-build\scripts\CMakeLists.txt;&quot;C:\Program Files\CMake 2.4\share\cmake-2.4\Templates\CMakeWindowsSystemConfig.cmake&quot;;F:\build\mysql-5.0.51a-winbuild\mysql-community-nt-5.0.51a-build\scripts\CMakeLists.txt;"
					Outputs="comp_sql.vcproj.cmake"/>
				</FileConfiguration>
				<FileConfiguration
					Name="RelWithDebInfo|Win32">
					<Tool
					Name="VCCustomBuildTool"
					Description="Building Custom Rule F:/build/mysql-5.0.51a-winbuild/mysql-community-nt-5.0.51a-build/scripts/CMakeLists.txt"
					CommandLine="&quot;C:\Program Files\CMake 2.4\bin\cmake.exe&quot; -HF:/build/mysql-5.0.51a-winbuild/mysql-community-nt-5.0.51a-build -BF:/build/mysql-5.0.51a-winbuild/mysql-community-nt-5.0.51a-build"
					AdditionalDependencies="F:\build\mysql-5.0.51a-winbuild\mysql-community-nt-5.0.51a-build\scripts\CMakeLists.txt;&quot;C:\Program Files\CMake 2.4\share\cmake-2.4\Templates\CMakeWindowsSystemConfig.cmake&quot;;F:\build\mysql-5.0.51a-winbuild\mysql-community-nt-5.0.51a-build\scripts\CMakeLists.txt;"
					Outputs="comp_sql.vcproj.cmake"/>
				</FileConfiguration>
			</File>
		<Filter
			Name="CMake Rules"
			Filter="">
			<File
				RelativePath="F:\build\mysql-5.0.51a-winbuild\mysql-community-nt-5.0.51a-build\scripts\CMakeFiles\GenFixPrivs.rule">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCustomBuildTool"
					Description=""
					CommandLine=""
					AdditionalDependencies="F:\build\mysql-5.0.51a-winbuild\mysql-community-nt-5.0.51a-build\scripts\mysql_fix_privilege_tables_sql.c;"
					Outputs="F:\build\mysql-5.0.51a-winbuild\mysql-community-nt-5.0.51a-build\scripts\CMakeFiles\GenFixPrivs"/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCustomBuildTool"
					Description=""
					CommandLine=""
					AdditionalDependencies="F:\build\mysql-5.0.51a-winbuild\mysql-community-nt-5.0.51a-build\scripts\mysql_fix_privilege_tables_sql.c;"
					Outputs="F:\build\mysql-5.0.51a-winbuild\mysql-community-nt-5.0.51a-build\scripts\CMakeFiles\GenFixPrivs"/>
				</FileConfiguration>
				<FileConfiguration
					Name="MinSizeRel|Win32">
					<Tool
					Name="VCCustomBuildTool"
					Description=""
					CommandLine=""
					AdditionalDependencies="F:\build\mysql-5.0.51a-winbuild\mysql-community-nt-5.0.51a-build\scripts\mysql_fix_privilege_tables_sql.c;"
					Outputs="F:\build\mysql-5.0.51a-winbuild\mysql-community-nt-5.0.51a-build\scripts\CMakeFiles\GenFixPrivs"/>
				</FileConfiguration>
				<FileConfiguration
					Name="RelWithDebInfo|Win32">
					<Tool
					Name="VCCustomBuildTool"
					Description=""
					CommandLine=""
					AdditionalDependencies="F:\build\mysql-5.0.51a-winbuild\mysql-community-nt-5.0.51a-build\scripts\mysql_fix_privilege_tables_sql.c;"
					Outputs="F:\build\mysql-5.0.51a-winbuild\mysql-community-nt-5.0.51a-build\scripts\CMakeFiles\GenFixPrivs"/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="F:\build\mysql-5.0.51a-winbuild\mysql-community-nt-5.0.51a-build\scripts\mysql_fix_privilege_tables_sql.c.rule">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCustomBuildTool"
					Description="Generating mysql_fix_privilege_tables_sql.c"
					CommandLine="$(OutDir)\comp_sql.exe mysql_fix_privilege_tables mysql_fix_privilege_tables.sql mysql_fix_privilege_tables_sql.c"
					AdditionalDependencies="F:\build\mysql-5.0.51a-winbuild\mysql-community-nt-5.0.51a-build\scripts\$(OutDir)\comp_sql.exe;F:\build\mysql-5.0.51a-winbuild\mysql-community-nt-5.0.51a-build\scripts\mysql_fix_privilege_tables.sql;"
					Outputs="F:\build\mysql-5.0.51a-winbuild\mysql-community-nt-5.0.51a-build\scripts\mysql_fix_privilege_tables_sql.c"/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCustomBuildTool"
					Description="Generating mysql_fix_privilege_tables_sql.c"
					CommandLine="$(OutDir)\comp_sql.exe mysql_fix_privilege_tables mysql_fix_privilege_tables.sql mysql_fix_privilege_tables_sql.c"
					AdditionalDependencies="F:\build\mysql-5.0.51a-winbuild\mysql-community-nt-5.0.51a-build\scripts\$(OutDir)\comp_sql.exe;F:\build\mysql-5.0.51a-winbuild\mysql-community-nt-5.0.51a-build\scripts\mysql_fix_privilege_tables.sql;"
					Outputs="F:\build\mysql-5.0.51a-winbuild\mysql-community-nt-5.0.51a-build\scripts\mysql_fix_privilege_tables_sql.c"/>
				</FileConfiguration>
				<FileConfiguration
					Name="MinSizeRel|Win32">
					<Tool
					Name="VCCustomBuildTool"
					Description="Generating mysql_fix_privilege_tables_sql.c"
					CommandLine="$(OutDir)\comp_sql.exe mysql_fix_privilege_tables mysql_fix_privilege_tables.sql mysql_fix_privilege_tables_sql.c"
					AdditionalDependencies="F:\build\mysql-5.0.51a-winbuild\mysql-community-nt-5.0.51a-build\scripts\$(OutDir)\comp_sql.exe;F:\build\mysql-5.0.51a-winbuild\mysql-community-nt-5.0.51a-build\scripts\mysql_fix_privilege_tables.sql;"
					Outputs="F:\build\mysql-5.0.51a-winbuild\mysql-community-nt-5.0.51a-build\scripts\mysql_fix_privilege_tables_sql.c"/>
				</FileConfiguration>
				<FileConfiguration
					Name="RelWithDebInfo|Win32">
					<Tool
					Name="VCCustomBuildTool"
					Description="Generating mysql_fix_privilege_tables_sql.c"
					CommandLine="$(OutDir)\comp_sql.exe mysql_fix_privilege_tables mysql_fix_privilege_tables.sql mysql_fix_privilege_tables_sql.c"
					AdditionalDependencies="F:\build\mysql-5.0.51a-winbuild\mysql-community-nt-5.0.51a-build\scripts\$(OutDir)\comp_sql.exe;F:\build\mysql-5.0.51a-winbuild\mysql-community-nt-5.0.51a-build\scripts\mysql_fix_privilege_tables.sql;"
					Outputs="F:\build\mysql-5.0.51a-winbuild\mysql-community-nt-5.0.51a-build\scripts\mysql_fix_privilege_tables_sql.c"/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="F:\build\mysql-5.0.51a-winbuild\mysql-community-nt-5.0.51a-build\scripts\mysql_fix_privilege_tables.sql.rule">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCustomBuildTool"
					Description="Generating mysql_fix_privilege_tables.sql"
					CommandLine="copy /b mysql_system_tables.sql + mysql_system_tables_fix.sql mysql_fix_privilege_tables.sql"
					AdditionalDependencies="F:\build\mysql-5.0.51a-winbuild\mysql-community-nt-5.0.51a-build\scripts\mysql_system_tables.sql;F:\build\mysql-5.0.51a-winbuild\mysql-community-nt-5.0.51a-build\scripts\mysql_system_tables_fix.sql;"
					Outputs="F:\build\mysql-5.0.51a-winbuild\mysql-community-nt-5.0.51a-build\scripts\mysql_fix_privilege_tables.sql"/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCustomBuildTool"
					Description="Generating mysql_fix_privilege_tables.sql"
					CommandLine="copy /b mysql_system_tables.sql + mysql_system_tables_fix.sql mysql_fix_privilege_tables.sql"
					AdditionalDependencies="F:\build\mysql-5.0.51a-winbuild\mysql-community-nt-5.0.51a-build\scripts\mysql_system_tables.sql;F:\build\mysql-5.0.51a-winbuild\mysql-community-nt-5.0.51a-build\scripts\mysql_system_tables_fix.sql;"
					Outputs="F:\build\mysql-5.0.51a-winbuild\mysql-community-nt-5.0.51a-build\scripts\mysql_fix_privilege_tables.sql"/>
				</FileConfiguration>
				<FileConfiguration
					Name="MinSizeRel|Win32">
					<Tool
					Name="VCCustomBuildTool"
					Description="Generating mysql_fix_privilege_tables.sql"
					CommandLine="copy /b mysql_system_tables.sql + mysql_system_tables_fix.sql mysql_fix_privilege_tables.sql"
					AdditionalDependencies="F:\build\mysql-5.0.51a-winbuild\mysql-community-nt-5.0.51a-build\scripts\mysql_system_tables.sql;F:\build\mysql-5.0.51a-winbuild\mysql-community-nt-5.0.51a-build\scripts\mysql_system_tables_fix.sql;"
					Outputs="F:\build\mysql-5.0.51a-winbuild\mysql-community-nt-5.0.51a-build\scripts\mysql_fix_privilege_tables.sql"/>
				</FileConfiguration>
				<FileConfiguration
					Name="RelWithDebInfo|Win32">
					<Tool
					Name="VCCustomBuildTool"
					Description="Generating mysql_fix_privilege_tables.sql"
					CommandLine="copy /b mysql_system_tables.sql + mysql_system_tables_fix.sql mysql_fix_privilege_tables.sql"
					AdditionalDependencies="F:\build\mysql-5.0.51a-winbuild\mysql-community-nt-5.0.51a-build\scripts\mysql_system_tables.sql;F:\build\mysql-5.0.51a-winbuild\mysql-community-nt-5.0.51a-build\scripts\mysql_system_tables_fix.sql;"
					Outputs="F:\build\mysql-5.0.51a-winbuild\mysql-community-nt-5.0.51a-build\scripts\mysql_fix_privilege_tables.sql"/>
				</FileConfiguration>
			</File>
		</Filter>
	</Files>
	<Globals>
	</Globals>
</VisualStudioProject>
